Repository FACG6/logicteca, pull requests merged in 2019-04, with the labels that each got.

#64 Search component
  client/src/App.js
  client/src/components/common components/search/index.jsx
  client/src/components/common components/search/style.css
Labels: waiting review

#67 Header component
  client/src/App.js
  client/src/components/Layout/Header/index.jsx
  client/src/components/Layout/Header/style.css
Labels: waiting review

#69 antDesign Library
  client/package-lock.json
  client/package.json
  client/src/App.js
  package-lock.json
Labels: urgent, waiting review

#66 Defaults
  client/src/App.css
  client/src/App.js
  client/src/components/Users/index.jsx
  client/src/components/Users/style.css
  client/src/components/utils/users.json
Labels: urgent, waiting review

#71 New project antd
  client/src/components/Projects/ProjectNew/TableMember/TableMember.jsx
  client/src/components/Projects/ProjectNew/TableMember/logic.js
  client/src/components/Projects/ProjectNew/TableMember/member.json
  client/src/components/Projects/ProjectNew/TableMember/style.css
  client/src/components/Projects/ProjectNew/index.jsx
  client/src/components/Projects/ProjectNew/style.css
Labels: waiting review

#75 Common components
  client/src/components/common components/search/index.jsx
  client/src/components/common components/search/style.css
  client/src/components/commonComponents/search/index.jsx
  client/src/components/commonComponents/search/style.css
Labels: waiting review

#73 Projects page
  client/src/components/Projects/index.jsx
  client/src/components/Projects/projectsTable/index.jsx
  client/src/components/Projects/projectsTable/style.css
  client/src/components/Projects/style.css
  client/src/components/utils/projects.js
Labels: waiting review

#84 add script for kill ports
  package.json
Labels: waiting review

#85 fix out-line and padding for inputs
  client/src/components/Projects/ProjectNew/style.css
Labels: waiting review

#82 Login
  client/src/components/Login/about/about.png
  client/src/components/Login/about/index.jsx
  client/src/components/Login/about/style.css
  client/src/components/Login/index.jsx
  client/src/components/Login/loginForm/index.jsx
  client/src/components/Login/loginForm/style.css
  client/src/components/Login/loginForm/user.png
  client/src/components/Login/style.css
Labels: waiting review

#90 improvement
  client/src/components/Projects/index.jsx
  client/src/components/Projects/style.css
Labels: waiting review

#89 Search component and logic
  client/src/components/commonComponents/search/index.jsx
  client/src/components/commonComponents/search/logic.js
  client/src/components/commonComponents/search/style.css
Labels: waiting review

#92 modify reade me file and also add schema file
  DatabaseSchema/schema.png
  README.md
Labels: waiting review

#81 add edit project page
  client/src/components/Projects/ProjectEdit/index.jsx
  client/src/components/Projects/ProjectEdit/style.css
  client/src/components/Projects/ProjectNew/TableMember/style.css
  client/src/components/Projects/ProjectNew/index.jsx
  client/src/components/commonComponents/TableMember/index.jsx
  client/src/components/commonComponents/TableMember/logic.js
  client/src/components/commonComponents/TableMember/member.json
  client/src/components/commonComponents/TableMember/projects.json
  client/src/components/commonComponents/TableMember/style.css
Labels: waiting review

#94 remove enterButton from SearchFor component coz no need for it
  client/src/components/commonComponents/search/index.jsx
Labels: waiting review

#93 Projects page
  client/src/components/Projects/index.jsx
  client/src/components/Projects/projectsTable/index.jsx
  client/src/components/Projects/projectsTable/style.css
  client/src/components/Projects/style.css
Labels: waiting review

#95 add NotFoundPage and login in app file
  client/src/App.js
  client/src/components/PageNotFound/index.jsx
  client/src/components/PageNotFound/style.css
Labels: waiting review

#98 Fix header style
  client/public/index.html
  client/src/App.js
  client/src/components/Layout/Header/style.css
Labels: urgent, waiting review

#97 Lato font
  client/public/index.html
Labels: urgent, waiting review

#99 Page not found
  client/src/components/PageNotFound/icons8-bug-90.png
  client/src/components/PageNotFound/index.jsx
  client/src/components/PageNotFound/style.css
Labels: waiting review

#102 Edit z-index to 3 to be over every thing in the page
  client/src/components/Layout/Header/style.css
  client/src/components/PageNotFound/style.css
  client/src/components/Projects/ProjectEdit/style.css
  client/src/components/Projects/ProjectNew/style.css
  client/src/components/Projects/style.css
Labels: waiting review

#72 Users component
  client/package-lock.json
  client/package.json
  client/src/components/Users/error/Error.jsx
  client/src/components/Users/error/style.css
  client/src/components/Users/form/index.jsx
  client/src/components/Users/form/style.css
  client/src/components/Users/helpers.js
  client/src/components/Users/index.jsx
  client/src/components/Users/menu/menu.jsx
  client/src/components/Users/notification/index.jsx
  client/src/components/Users/select/index.jsx
  client/src/components/Users/select/style.css
  client/src/components/Users/style.css
  client/src/components/utils/users.json
  client/src/utils/users.json
Labels: waiting review

#106 Database
  .gitignore
  package-lock.json
  package.json
  server/database/config/connection.js
  server/database/config/dbBuild.js
  server/database/config/dbBuild.sql
Labels: back-end, waiting review

#104 fix bug in displaying and hiding password button, remove validation f…
  client/src/components/Users/index.jsx
  client/src/components/Users/notification/index.jsx
Labels: approved

#119 modify sql build file
  server/database/config/connection.js
  server/database/config/dbBuild.sql
Labels: back-end, waiting review

#115 Schema fake data
  server/database/config/dbBuildFakeData.sql
  server/database/config/insertFakeData.js
Labels: data-base, waiting review

#118 Scrum tasks query
  package.json
  server/database/config/connection.js
  server/database/queries/selectProjectDetails.js
  server/database/queries/selectProjects.js
  server/database/queries/selectScrumTasks.js
  test/index.js
  test/server/projectDetailsQuery.test.js
  test/server/projectsQuery.test.js
  test/server/scrumTasks.test.js
  test/server/test.js
Labels: back-end, db-query, waiting review

#117 Project details query
  server/database/queries/selectProjectDetails.js
  test/server/projectDetailsQuery.test.js
Labels: back-end, db-query, waiting review

#116 Select All Project query
  server/database/queries/selectProjects.js
Labels: back-end, db-query, waiting review

#113 Database queries (selectUsers)
  server/database/config/dbBuild.js
  server/database/queries/insertUser.js
  server/database/queries/selectUsers.js
  test/index.js
  test/server/selectUsers.js
Labels: waiting review

#120 Select scrums project
  server/database/queries/selectProjectScrums.js
  test/index.js
  test/server/projectScrums.js
Labels: waiting review

#122 Controllers
  server/app.js
  server/controllers/index.js
  server/controllers/projects/deleteProject.js
  server/controllers/projects/getProject.js
  server/controllers/projects/getProjects.js
  server/controllers/projects/index.js
  server/controllers/projects/post.js
  server/controllers/projects/put.js
  server/controllers/scrums/deleteScrum.js
  server/controllers/scrums/getScrums.js
  server/controllers/scrums/getTasks.js
  server/controllers/scrums/index.js
  server/controllers/scrums/post.js
  server/controllers/scrums/put.js
  server/controllers/tasks/deleteTask.js
  server/controllers/tasks/index.js
  server/controllers/tasks/post.js
  server/controllers/tasks/put.js
  server/controllers/users/deleteUser.js
  server/controllers/users/get.js
  server/controllers/users/index.js
  server/controllers/users/post.js
  server/controllers/users/put.js
Labels: back-end, waiting review

#125 add a condition to rebuild sql
  server/database/config/dbBuild.js
Labels: urgent

#127 Controllers
  server/app.js
  server/controllers/index.js
  server/controllers/projects/deleteProject.js
  server/controllers/projects/getProject.js
  server/controllers/projects/getProjects.js
  server/controllers/projects/index.js
  server/controllers/projects/post.js
  server/controllers/projects/put.js
  server/controllers/scrums/deleteScrum.js
  server/controllers/scrums/getScrums.js
  server/controllers/scrums/getTasks.js
  server/controllers/scrums/index.js
  server/controllers/scrums/post.js
  server/controllers/scrums/put.js
  server/controllers/tasks/deleteTask.js
  server/controllers/tasks/index.js
  server/controllers/tasks/post.js
  server/controllers/tasks/put.js
  server/controllers/users/deleteUser.js
  server/controllers/users/get.js
  server/controllers/users/index.js
  server/controllers/users/post.js
  server/controllers/users/put.js
  server/index.js
Labels: back-end, waiting review

#126 edit selectProjectScrums test
  test/server/projectScrums.js
Labels: waiting review

#132 Change UUID
  server/controllers/projects/getProject.js
  server/database/config/dbBuild.sql
  server/database/config/dbBuildFakeData.sql
Labels: back-end, data-base, urgent

#128 Get user route
  server/controllers/users/get.js
  server/router/index.js
  test/index.js
  test/server/routes/getUsers.js
Labels: waiting review

#142 Install happi joi
  package-lock.json
  package.json
Labels: back-end, waiting review

#140 add on delete cascade on scrums and tasks tables
  server/database/config/dbBuild.sql
Labels: back-end, t1h, waiting review

#130 Get projects route
  server/controllers/projects/getProjects.js
  test/index.js
  test/server/routes/getProjectsRoute.js
Labels: back-end, t1h, waiting review

#129 Project new route
  server/controllers/projects/index.js
  server/controllers/projects/post.js
  server/database/queries/insertProject.js
  test/index.js
  test/server/projectDetailsQuery.test.js
  test/server/projectNewQuery.test.js
  test/server/router/projectNewRoute.test.js
  test/server/scrumTasks.test.js
Labels: back-end, request changes

#139 Insert task query
  server/database/queries/insertTask.js
  test/index.js
  test/server/insertNewTask.js
Labels: waiting review

#145 edit sql, rmoving reference to user_id
  server/database/config/dbBuild.sql
  server/database/config/insertFakeData.js
  server/database/queries/selectScrumTasks.js
  test/server/scrumTasks.test.js
  test/server/selectUsers.js
Labels: urgent

#155 fix inserFakeData bug
  server/database/config/insertFakeData.js
Labels: urgent, waiting review

#157 set database in travis and add a script for test locally
  .travis.yml
  package.json
  server/database/config/insertFakeData.js
  test/index.js
Labels: back-end, urgent, waiting review

#152 delete scrum route and it test
  server/controllers/scrums/deleteScrum.js
  server/database/queries/deleteScum.js
  test/index.js
  test/server/projectDetailsQuery.test.js
  test/server/routes/deleteScrumRoute.js
  test/server/scrumTasks.test.js
Labels: back-end, waiting review

#136 Get project route
  server/controllers/projects/getProject.js
  server/controllers/projects/helper.js
  server/database/queries/selectProjectDetails.js
  test/index.js
  test/server/projectDetailsQuery.test.js
  test/server/routes/getProjectRoute.js
Labels: back-end, t1d, waiting review

#143 Post user route
  server/controllers/users/helpers/hashPassword.js
  server/controllers/users/helpers/validateUser.js
  server/controllers/users/index.js
  server/controllers/users/post.js
  server/database/queries/checkUser.js
  server/database/queries/insertUser.js
  test/index.js
  test/server/insertUser.js
  test/server/router/postUser.js
Labels: waiting review

#144 Delete project route
  server/controllers/projects/deleteProject.js
  server/database/queries/deleteProject.js
  test/index.js
  test/server/routes/deleteProjectRoute.js
Labels: back-end, t1h, waiting review

#147 Post scrum route
  server/controllers/scrums/helpers/validateNewScrum.js
  server/controllers/scrums/index.js
  server/controllers/scrums/post.js
  server/database/queries/insertScrum.js
  test/index.js
  test/server/insertScrumQuery.js
  test/server/routes/postScrumRoute.js
Labels: back-end, t2h

#148 Project edit route
  server/controllers/projects/post.js
  server/controllers/projects/put.js
  server/database/config/insertFakeData.js
  server/database/queries/updateProject.js
  test/index.js
  test/server/routes/projectEditRoute.test.js
  test/server/routes/projectNewRoute.test.js
Labels: back-end, waiting review

#149 Delete user route
  server/controllers/users/deleteUser.js
  server/controllers/users/index.js
  server/database/queries/deleteUser.js
  server/database/queries/selectId.js
  test/index.js
  test/server/deleteUser.js
  test/server/routes/deleteUser.route.js
  test/server/routes/postUser.js
Labels: waiting review

#150 Put user route
  server/controllers/users/index.js
  server/controllers/users/put.js
  server/database/queries/updateUser.js
  test/index.js
  test/server/routes/updateUser.js
  test/server/updateUser.js
Labels: waiting review

#134 Scrum route | GET
  server/controllers/scrums/getScrums.js
  server/controllers/scrums/getTasks.js
  server/controllers/scrums/index.js
  test/index.js
  test/server/getScrumRoute.js
Labels: waiting review

#146 Task Route | POST
  server/controllers/tasks/post.js
  test/index.js
  test/server/routes/insertTaskRoute.js
  test/server/scrumTasks.test.js
Labels: waiting review

#164 fix bug in test
  test/server/routes/projectEditRoute.test.js
Labels: back-end, waiting review

#163 Update Scrum Route
  server/controllers/scrums/put.js
  server/database/queries/updateScrum.js
  test/index.js
  test/server/routes/putScrumRoute.test.js
Labels: back-end, waiting review

#169 Install axios
  client/package-lock.json
  client/package.json
  package-lock.json
  package.json
Labels: front-end, urgent, waiting review

#172 Front end auth
  client/src/App.js
  client/src/auth/index.jsx
  client/src/auth/isAuth.js
  client/src/components/Layout/Header/index.jsx
  client/src/components/Login/index.jsx
  client/src/components/Login/loginForm/index.jsx
Labels: front-end, front-end-auth, waiting review

#173 add middleware for auth to check cookie
  server/controllers/index.js
  server/controllers/middleware/authentication.js
  server/controllers/middleware/helpers.js
Labels: back-end, waiting review

#176 add logout route
  server/controllers/index.js
  server/controllers/logout/index.js
Labels: back-end, waiting review

#166 Bug post controller
  server/controllers/users/post.js
Labels: waiting review

#178 Front logout
  client/src/App.js
  client/src/auth/index.jsx
  client/src/auth/isAuth.js
  client/src/components/Layout/Header/index.jsx
  client/src/components/Users/notification/index.jsx
Labels: waiting review

#182 fix test with add cookie
  server/controllers/index.js
  test/index.js
  test/server/getScrumRoute.js
  test/server/routes/deleteProjectRoute.js
  test/server/routes/deleteScrumRoute.js
  test/server/routes/deleteUser.route.js
  test/server/routes/getProjectRoute.js
  test/server/routes/getProjectsRoute.js
  test/server/routes/getScrumRoute.js
  test/server/routes/getUsers.js
  test/server/routes/insertTaskRoute.js
  test/server/routes/postScrumRoute.js
  test/server/routes/postUser.js
  test/server/routes/projectEditRoute.test.js
  test/server/routes/projectNewRoute.test.js
  test/server/routes/putScrumRoute.test.js
  test/server/routes/updateUser.js
Labels: back-end, waiting review

#174 Login backend route | POST
  server/controllers/index.js
  server/controllers/login/index.js
  server/controllers/login/login.js
  server/database/config/dbBuildFakeData.sql
  test/index.js
  test/server/routes/loginPostRoute.js
Labels: waiting review
