Repository FACG6/logicteca, pull requests merged in 2019-05, with the labels that each got.

#185 send the payload with res
  server/controllers/login/login.js
Labels: waiting review

#187 Backend authentication route
  server/controllers/index.js
  server/controllers/isAuth/index.js
Labels: back-end, server-routes, waiting review

#191 add two scripts for heroku deploy
  package.json
Labels: deploy, urgent, waiting review

#196 Backend refactor
  server/controllers/projects/getScrums.js
  server/controllers/projects/index.js
  server/controllers/projects/post.js
  server/controllers/projects/put.js
  server/database/queries/selectProjects.js
Labels: back-end, db-query, server-routes, urgent, waiting review

#188 Front end requests Projects
  client/src/App.js
  client/src/auth/index.jsx
  client/src/auth/isAuth.js
  client/src/components/Login/loginForm/index.jsx
  client/src/components/Project/index.jsx
  client/src/components/Projects/ProjectEdit/index.jsx
  client/src/components/Projects/ProjectNew/index.jsx
  client/src/components/Projects/index.jsx
  client/src/components/commonComponents/TableMember/index.jsx
Labels: front-end, waiting review

#198 add get users and update user
  client/src/components/Users/form/index.jsx
  client/src/components/Users/index.jsx
  client/src/components/Users/menu/menu.jsx
  client/src/components/Users/select/index.jsx
  package.json
  server/controllers/users/helpers/validateUser.js
  server/controllers/users/index.js
  server/controllers/users/put.js
  server/database/config/dbBuildFakeData.sql
  server/database/queries/updateUser.js
  test/index.js
  test/server/routes/updateUser.js
  test/server/updateUser.js
Labels: front-end, waiting review

#193 TASK | DELETE
  server/controllers/tasks/deleteTask.js
  server/database/queries/deleteTask.js
  test/index.js
  test/server/routes/deleteTaskRoute.js
Labels: back-end, urgent, waiting review

#202 make axios to get scrums and insert scrums
  client/src/App.js
  client/src/components/Project/index.jsx
  client/src/components/Projects/ProjectEdit/index.jsx
  server/controllers/index.js
  server/controllers/projects/getScrums.js
  server/controllers/scrums/helpers/validateNewScrum.js
  server/controllers/scrums/index.js
  server/database/queries/selectProjectScrums.js
  test/server/routes/deleteTaskRoute.js
  test/server/routes/postUser.js
Labels: front-end, waiting review

#205 tasks component requests
  client/src/App.js
  client/src/auth/isAuth.js
  client/src/components/Project/Scrums/index.jsx
  client/src/components/Project/Scrums/select/index.jsx
  client/src/components/Project/index.jsx
  client/src/components/Projects/index.jsx
  server/controllers/index.js
  server/controllers/projects/helper.js
  server/database/config/insertFakeData.js
  server/database/queries/selectProjectDetails.js
  server/database/queries/selectScrumTasks.js
Labels: in-progress

#217 Client Authentication refactor
  client/src/App.js
  client/src/auth/LogedoutRoute.jsx
  client/src/auth/PrivateRoute.jsx
  client/src/auth/index.jsx
  client/src/components/Layout/Header/index.jsx
  client/src/components/Login/loginForm/index.jsx
  client/src/components/Login/loginForm/style.css
  server/controllers/index.js
  server/controllers/isAuth/index.js
Labels: waiting review

#244 Fix travis
  server/controllers/projects/getProject.js
  server/controllers/projects/post.js
  server/controllers/tasks/index.js
  server/controllers/tasks/post.js
  server/database/config/insertFakeData.js
  server/database/queries/selectProjectDetails.js
  server/database/queries/selectUsers.js
  test/server/insertNewTask.js
  test/server/projectDetailsQuery.test.js
  test/server/routes/getProjectRoute.js
  test/server/routes/getScrumRoute.js
  test/server/routes/insertTaskRoute.js
  test/server/routes/projectNewRoute.test.js
  test/server/scrumTasks.test.js
Labels: waiting review

#251 Delete scrum bug
  client/src/components/Project/Scrum/index.jsx
Labels: waiting review

#254 Add scrum bug
  client/src/components/Project/Scrum/index.jsx
Labels: waiting review

#253 solve TableMember appearance problem
  client/src/components/Projects/ProjectEdit/index.jsx
  client/src/components/commonComponents/TableMember/index.jsx
Labels: t1h

#256 Refactor tasks
  client/src/components/Project/Scrum/TaskTable/index.jsx
  client/src/components/Project/Scrum/utilis/filter.js
  client/src/components/Project/Scrum/utilis/helpers.js
  client/src/components/Project/Scrum/utilis/sort.js
Labels: waiting review

#262 Edit task bug
  client/src/components/Project/Scrum/utilis/helpers.js
  server/controllers/tasks/put.js
  server/database/queries/updateTask.js
Labels: waiting review

#276 fix: add focus to the new row
  client/src/components/Project/Scrum/TaskTable/TaskColumns.jsx
  client/src/components/Project/Scrum/TaskTable/index.jsx
  client/src/components/Project/Scrum/utilis/helpers.js
  client/src/components/Users/form/index.jsx
  client/src/components/Users/index.jsx
Labels: waiting review
